### ISSUE TITLE
Issue building 29 Oct 2020 version of LAMMPS with the ljlambda pair style

### ISSUE THREAD

**Issue by al979** [azamat-rizuan/HPS-SS-model#1]
Hi Azamat,

I was trying to build the 29 Oct 2020 version of LAMMPS with the code in this repository, but I have been unable to. I have attached the error messages at the end of this issue.

Also, the header file corresponding to lmp2020_pair_ljlambda.cpp (within 1. LAMMPS_subroutines) does not appear to be present anywhere in this repository. I tried writing a corresponding header file but I still get the following error:

```
/projects/f_rcr78_1/AL/lammpsForMittalCG/src/angle_bch.cpp: In member function ‘virtual void LAMMPS_NS::AngleBCH::coeff(int, char**)’:
/projects/f_rcr78_1/AL/lammpsForMittalCG/src/angle_bch.cpp:195:10: error: ‘class LAMMPS_NS::Force’ has no member named ‘bounds’; did you mean ‘bond’?
 195 |  force->bounds(FLERR,arg[0],atom->nangletypes,ilo,ihi);
   |     ^~~~~~
   |     bond
/projects/f_rcr78_1/AL/lammpsForMittalCG/src/angle_bch.cpp:197:31: error: ‘class LAMMPS_NS::Force’ has no member named ‘numeric’
 197 |  double epsilon_one = force->numeric(FLERR,arg[1]);
   |                ^~~~~~~
make[2]: *** [CMakeFiles/lammps.dir/projects/f_rcr78_1/AL/lammpsForMittalCG/src/angle_bch.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/lammps.dir/all] Error 2
make: *** [all] Error 2

```
Let me know if there are any other details that I can include and thank you so much in advance!

**Comment by azamat-rizuan** [comment]
I added the corresponding header file: pair_ljlambda.h
